pipeline {
    agent any

    parameters{
        gitParameter(name: 'BRANCH_TO_DEPLOY', branch: '', branchFilter: 'origin/(.*)', defaultValue: 'develop',
        quickFilterEnabled: false, selectedValue: 'NONE', sortMode: 'NONE', tagFilter: '*',
        type: 'GitParameterDefinition', useRepository: 'https://github.com/yanpgabriel/DuckApp.git')

        string(name: 'DOCKER_IMAGE', defaultValue: 'localhost:5000/duckapp:pi', trim: true)
    }

    environment {
        GIT_HASH = sh(script: 'git rev-parse --short HEAD', returnStdout: true).trim()
        COMMITER_NAME = sh(script: 'git show -s --pretty=%an', returnStdout: true).trim()
        COMMITER_EMAIL = sh(script: 'git show -s --format=%ae', returnStdout: true).trim()
        COMMITER_COMMENT = sh(script: 'git show -s --pretty=%B', returnStdout: true).trim()

        NAMESPACE = 'duck-namespace'
    }

    options {
        buildDiscarder(logRotator(numToKeepStr: '5'))
        disableConcurrentBuilds(abortPrevious: true)
    }

    stages {
        stage('Checkout') {
            steps {
                // Limpa o Workspace
                cleanWs()
                sh "echo Clonando a branch selecionada '${BRANCH_TO_DEPLOY}'"
                // Baixa o codigo
                git branch: "${BRANCH_TO_DEPLOY}", url: 'https://github.com/yanpgabriel/DuckApp.git'
            }
        }
        stage('Build') {
            agent {
              docker {
                image 'node:18.14.2-alpine'
                reuseNode true
              }
            }
            steps {
                sh 'npm install'
                sh 'npm run build'
            }
        }
        stage('Gerar arquivo compactado') {
            steps {
                sh 'tar czf duckapp.tar.gz dist/DuckApp'
            }
        }
        stage('Arquivar artefato') {
            steps {
                archiveArtifacts allowEmptyArchive: true, artifacts: 'duckapp.tar.gz', followSymlinks: false, onlyIfSuccessful: true
            }
        }
        stage('Gerar Imagem Docker') {
            steps {
                sh "docker build -f src/docker/Dockerfile -t ${DOCKER_IMAGE} ."
            }
        }
        stage('Publicar Imagem Docker') {
            steps {
                sh "docker push ${DOCKER_IMAGE}"
            }
        }
    }
}
